export const App_ABI = [
  {
    type: 'function',
    name: 'depositRelayerFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolIds',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolInfo',
    inputs: [{ name: 'poolId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'token', type: 'address' },
          { name: 'depositFeeBPS', type: 'uint16' },
          { name: 'withdrawFeeBPS', type: 'uint16' },
          { name: 'accumulatedFee', type: 'uint128' },
          { name: 'viewerPK', type: 'uint256[2]' },
          { name: 'freezerPK', type: 'uint256[2]' },
          { name: 'transferMaxAmount', type: 'uint128' },
          { name: 'withdrawMaxAmount', type: 'uint128' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'poolId', type: 'uint256' },
      { name: 'amount', type: 'uint128' },
      { name: 'userPK', type: 'uint256[2]' },
      { name: 'nonce', type: 'uint256' },
      { name: '', type: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'getArray',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'digest',
    inputs: [],
    outputs: [
      { name: 'merkleTreeRoot', type: 'uint256' },
      { name: 'currentArrayHash', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalElements',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'merkleRoots',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'ArrayMergedToTree',
    inputs: [
      { name: 'batchIndex', type: 'uint256', indexed: true },
      { name: 'newRoot', type: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
] as const;
